apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "krakend.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "krakend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.krakend.autoscaling.enabled }}
  replicas: {{ .Values.krakend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "krakend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/krakend-config: {{ include (print $.Template.BasePath "/krakend/configmap.yaml") . | sha256sum }}
        {{- if and .Values.krakend.tls.enabled (not .Values.krakend.tls.existingSecret) }}
        checksum/krakend-cert: {{ include (print $.Template.BasePath "/krakend/secret.yaml") . | sha256sum }}
        {{- end }}
      labels:
        {{- include "krakend.labels" . | nindent 8 }}
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: {{.Values.krakend.dns.ndots | quote}}
      {{- with .Values.krakend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.chartNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.chartNodeSelector }}
        {{- with .Values.krakend.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.krakend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.krakend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.krakend.podSecurityContext | nindent 8 }}
      containers:
        - name: krakend
          command: [ "/usr/bin/krakend" ]
          args: [ "run", "-d", "-c", "/etc/krakend/krakend.json", "-p", "8080" ]
          securityContext:
            {{- toYaml .Values.krakend.securityContext | nindent 12 }}
          image: "{{ .Values.krakend.image.repository }}:{{ .Values.krakend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.krakend.image.pullPolicy }}
          ports:
            - name: api
              containerPort: {{ .Values.krakend.service.ports.api.containerPort }}
              protocol: {{ .Values.krakend.service.ports.api.protocol }}
          resources:
            {{- toYaml .Values.krakend.resources | nindent 12 }}
          volumeMounts:
          - name: krakend-config
            mountPath: /etc/krakend/krakend.json
            subPath: krakend.json
          {{- if .Values.krakend.tls.enabled }}
          - name: krakend-cert
            mountPath: /etc/certs
            readOnly: true
          {{- end }}
      volumes:
        - name: krakend-config
          configMap:
            name: {{ include "krakend.configmapName" . }}
        {{- if .Values.krakend.tls.enabled }}
        - name: krakend-cert
          secret:
            {{- if .Values.krakend.tls.existingSecret }}
            secretName: {{ .Values.krakend.tls.existingSecret }}
            {{- else}}
            secretName: {{ include "krakend.fullname" . }}-secret
            {{- end }}
            items:
              - key: cert.pem
                path: cert.pem
              - key: key.pem
                path: key.pem
        {{- end }}
